version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(levelname)s: %(message)s'
  precise:
    format: '%(asctime)s; %(filename)s; %(levelname)s; %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  tsapp_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    level: DEBUG
    filename: 'logs/tsapplog'
    when: S
    delay: True
loggers:
  tsapplogger:
    handlers: [tsapp_file]
root:
  level: DEBUG
  handlers: [console]
