version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(levelname)s: %(message)s'
  precise:
    format: '%(asctime)s; %(filename)s; %(levelname)s; %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  setup_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    level: DEBUG
    filename: 'logs/setuplog'
    when: D
    delay: True
  ops_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    level: DEBUG
    filename: 'logs/opslog'
    when: D
    delay: True
  tsapp_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    level: DEBUG
    filename: 'logs/tsapplog'
    when: D
    delay: True
  tsabatch_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    level: DEBUG
    filename: 'logs/tsabatchlog'
    when: D
    delay: True
loggers:
  tsapplogger:
    handlers: [tsapp_file]
  tsabatchlogger:
    handlers: [tsabatch_file]
  setuplogger:
    handlers: [setup_file]
  opslogger:
    handlers: [ops_file]
  notebooklogger:
    handlers: [console]
root:
  level: DEBUG
  handlers: [console]
